// Generated by CoffeeScript 1.3.1
(function() {
  var Bomb,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Bomb = (function() {

    Bomb.name = 'Bomb';

    Bomb.SIZE = 50;

    function Bomb(x, y) {
      this.countDown = __bind(this.countDown, this);

      this.drop = __bind(this.drop, this);
      this.pos = {
        x: x,
        y: y
      };
      this.body = document.getElementsByTagName("body")[0];
      this.state = 'planted';
      this.count = 3;
      this.drop();
    }

    Bomb.prototype.drop = function() {
      this.bomb = document.createElement("div");
      this.bomb.innerHTML = this.count;
      this.body.appendChild(this.bomb);
      this.bomb.style['zIndex'] = "9999";
      this.bomb.style['fontFamily'] = "verdana";
      this.bomb.style['width'] = "" + Bomb.SIZE + "px";
      this.bomb.style['height'] = "" + Bomb.SIZE + "px";
      this.bomb.style['display'] = 'block';
      this.bomb.style['borderRadius'] = "" + Bomb.SIZE + "px";
      this.bomb.style['WebkitBorderRadius'] = "" + Bomb.SIZE + "px";
      this.bomb.style['MozBorderRadius'] = "" + Bomb.SIZE + "px";
      this.bomb.style['fontSize'] = '18px';
      this.bomb.style['color'] = '#fff';
      this.bomb.style['lineHeight'] = "" + Bomb.SIZE + "px";
      this.bomb.style['background'] = '#000';
      this.bomb.style['position'] = 'absolute';
      this.bomb.style['top'] = "" + (this.pos.y - Bomb.SIZE / 2) + "px";
      this.bomb.style['left'] = "" + (this.pos.x - Bomb.SIZE / 2) + "px";
      this.bomb.style['textAlign'] = "center";
      this.bomb.style['WebkitUserSelect'] = 'none';
      this.bomb.style['font-weight'] = 700;
      return setTimeout(this.countDown, 1000);
    };

    Bomb.prototype.countDown = function() {
      this.state = 'ticking';
      this.count--;
      this.bomb.innerHTML = this.count;
      if (this.count > 0) {
        return setTimeout(this.countDown, 1000);
      } else {
        return this.explose();
      }
    };

    Bomb.prototype.explose = function() {
      this.bomb.innerHTML = '';
      return this.state = 'explose';
    };

    Bomb.prototype.exploded = function() {
      this.state = 'exploded';
      this.bomb.innerHTML = '';
      this.bomb.style['fontSize'] = '12px';
      return this.bomb.style['opacity'] = 0.05;
    };

    return Bomb;

  })();

  this.Bomb = Bomb;

}).call(this);
